export const paths = {
  home: '/',
  products: '/produtos',
  product: (slug: string) => `/produto/${slug}`,
  category: (slug: string) => `/produtos?categoria=${slug}`,
  cart: '/carrinho',
  checkout: '/checkout',
  orderConfirmation: (orderNumber: string) => `/checkout/confirmacao/${orderNumber}`,
  login: '/login',
  signup: '/cadastro',
  forgotPassword: '/recuperar-senha',
  resetPassword: '/redefinir-senha',
  about: '/sobre',
  contact: '/contato',
  events: '/eventos',
  returnsPolicy: '/politica-de-trocas',
  privacyPolicy: '/politica-de-privacidade',
  shippingPolicy: '/politica-de-envio',

  account: '/minha-conta',
  accountAddresses: '/minha-conta/enderecos',
  accountOrders: '/minha-conta/pedidos',
  accountOrder: (orderNumber: string) => `/minha-conta/pedidos/${orderNumber}`,
  accountFavorites: '/minha-conta/favoritos',
  accountPassword: '/minha-conta/senha',

  admin: '/admin',
  adminProducts: '/admin/produtos',
  adminProductNew: '/admin/produtos/novo',
  adminProduct: (id: string) => `/admin/produtos/${id}`,
  adminCategories: '/admin/categorias',
  adminOrders: '/admin/pedidos',
  adminOrder: (id: string) => `/admin/pedidos/${id}`,
  adminCoupons: '/admin/cupons',
  adminBanners: '/admin/banners',
  adminEvents: '/admin/eventos',
  adminSettings: '/admin/configuracoes',
  adminTeam: '/admin/equipe',
} as const
